### ISSUE TITLE
General Retrospective for January 2024 Releases

### ISSUE THREAD

**Issue by adamfarley** [adoptium/temurin#13]
**Summary**

A retrospective for all efforts surrounding the titular releases. 

All community members are welcome to contribute to the agenda via comments below.

This will be a virtual meeting after the release, with at least a week of notice in the #release Slack channel.

On the day of the meeting we'll review the agenda and add a list of actions at the end.

Invited: Everyone.

**Time, Date, and URL**

Time: 2pm GMT, 9am EST
Date: Monday, 29th of January
URL: https://eclipse.zoom.us/j/85862065826?pwd=yXE1cYzqn2MnHv0BSq36jaTlAxqGxq.1

**Details**

Retrospective Owner Tasks (in order):

- [x] Post retro URL in \#Release around the start of the new release.
- [x] Copy actions from previous retrospectives into this issue, ignoring anything ticked.
  - Include owner names.
- [x] Wait until most builds are released, with no clear signs of additional respins.
- [x] Announce the retrospective's date + time on \#Release a week before.
- [x] Host the retrospective:
  - [x] Tick completed actions from last retrospective/s.
  - [x] Go through the agenda.
  - [x] Create a tickable list of actions.
  - [x] When the meeting is complete, raise issues for all actions and add them to the current iteration.
- [x] Create a new retrospective issue for the next release.
- [x] Set a calendar reminder so you remember to do step 1 before the next release.
- [x] Close this issue.

**Comment by adamfarley** [comment]
Actions from previous retrospectives:

**[September/October 2023](https://github.com/adoptium/temurin/issues/4):**
- [ ] Stewart: Make this change to website banner: https://github.com/adoptium/temurin/issues/4#issuecomment-1766668066
- [ ] Jie: To fix [this test issue](https://github.com/adoptium/temurin/issues/4#issuecomment-1771771923) upstream by making test more robust in regards to the "sleep" operation.
- [ ] Shelley - To update the release checklist to include "create the release draft for the next release" as a post-build step, to enable us to add "notable updates" as comments over time.

**[July 2023](https://github.com/adoptium/adoptium/issues/240#issuecomment-1662062556):**
- [x] Stewart: To make an issue for reviewing filename expression in RELEASING.md. https://github.com/adoptium/adoptium/issues/240#issuecomment-1645803026 - Raised https://github.com/adoptium/temurin/issues/4
- [ ] Scott: To raise issue for regular installer testing (build installer, test it, upload it, download it, install it, java -version).
- [x] Stewart: To discuss future plans for build scheduling at the next community retrospective (ea builds, testing, etc).
    https://docs.google.com/document/d/1oaU8GA_3F8DDzjeZujY10fiyRS-vKdF5rE0eAhAascY/edit#

**[March 2023](https://github.com/adoptium/adoptium/issues/219):**
- [ ] Trial the automatic rerun feature for Jenkins test jobs prior to April release to see if we may want to use it for April. https://github.com/adoptium/ci-jenkins-pipelines/issues/777
  - To roll over into next retro.

**Comment by adamfarley** [comment]
Topics rolled-over from last retrospective:

<details>
<summary> 1. "Permission to publish" requests can be forgotten. </summary>
  - One solution: Some form of Slack bot that recognises requests to publish, and notifies the poster once the required +1's have been accumulated. This bot could also supply a link that populates all of the relevant parameters correctly, e.g. "Grinder/parambuild/?SDK_RESOURCE=upstream&etcetc".
Said bot could also remind the poster if the expected binary isn't present in the correct repository within an acceptable time period.
Notes:
- If we do do this, we should make sure it can expanded easily, for future functionality.
- This bot would need to populate parameters in a way that plays well with [this issue](https://github.com/adoptium/temurin-build/issues/3449).
- Could such a bot help close the remaining tasks in [this issue](https://github.com/adoptium/github-release-scripts/issues/85)?
(edited)

Discussion so far:
- Should we create a new channel for "permission to publish" requests, so they don't get drowned out? (Update: PMC does not think this should be pursued)
- Asking people to include confirmations/publish job links in the thread under a request.
- For the release champion to scan for these.
- To have some manner of automation relating to the TCK status and release status tables.
</details>

<details>
<summary>2. The task to update support dates is marked as completed, but we have received [an issue](https://github.com/adoptium/adoptium.net/issues/2443) to update them as they were not done.</summary>
If it helps, I think this change was made on November 2nd at 2:02 PM GMT.
One solution could be to automate this (e.g. If NextRelease != "EOSL" then NextRelease=x+10), so when every primary platform has been published, a PR is generated and Slack is notified for approval.
</details>

**Comment by Haroon-Khel** [comment]
Corrected the release pipeline generator link in RELEASING.md in the build repo from https://ci.adoptium.net/job/build-scripts/job/utils/job/release-build-pipeline-generator/ to https://ci.adoptium.net/job/build-scripts/job/utils/job/release-pipeline-generator/

**Comment by smlambert** [comment]
Update release checklist template to remove arm32 from jdk21 table

**Comment by Haroon-Khel** [comment]
The release checklist maybe out of date in regards to which builds to disable during release week. Currently the checklist suggests disabling standard and evaluation builds, where as historically we disable nightly testing only. Discuss what is most suitable

**Comment by smlambert** [comment]
Recommend that we recreate this PR https://github.com/openjdk/jdk/pull/14942 to deal with issues with jtreg tests seen in AQAvit testing (see https://github.com/adoptium/aqa-tests/issues/4960#issuecomment-1890821702).

**Comment by smlambert** [comment]
Recommendation to improve Deep History view https://github.com/adoptium/aqa-test-tools/issues/837

**Comment by smlambert** [comment]
Increased number of disconnects seen with Orka machines (see https://github.com/adoptium/aqa-tests/issues/4960#issuecomment-1890964598 which references https://github.com/adoptium/infrastructure/issues/2536 and [Slack thread](https://adoptium.slack.com/archives/C53GHCXL4/p1705064146629879) for details).

**Comment by smlambert** [comment]
https://github.com/adoptium/infrastructure/issues/2885#issuecomment-1890709946 - No longer have Windows machines where certain jdk_tools tests can pass, hit a Wix toolset configuration error on all of our current set of Windows machines.

**Comment by sophia-guo** [comment]
https://github.com/adoptium/aqa-tests/issues/4821#issuecomment-1781250210 -
jdk_jdi_jdk8_2 passed, jdk_util_2 needs rerunning on odroid - both odroids are offline

**Comment by sophia-guo** [comment]
Double check if tap files of the rerun test builds are collected or archived to upstream pipeline jobs.

**Comment by Haroon-Khel** [comment]
https://adoptium.slack.com/archives/CLCFNV2JG/p1705426218260209

Release trigger scripts will add an extra _adopt suffix to tags even if there already is one
https://github.com/adoptium/mirror-scripts/blob/2079f4b2359de21a2ab0d4443664f31c3593b201/triggerReleasePipeline.sh#L67

```
Expected release tag: jdk8u402
Latest GA tag: jdk8u402-b05-dryrun-ga_adopt
jdk8u402-b05-dryrun-ga_adopt commit SHA: 1736327cb528b638d21e9fac3b63d321efb9d12e
Latest build tag pointing to 1736327cb528b638d21e9fac3b63d321efb9d12e: jdk8u402-b05_adopt
We will proceed with jdk8u402-b05-dryrun-ga_adopt to trigger build
No jdk8u402-b05_adopt_adopt tag found yet, will sleep 10 minutes and check again
No jdk8u402-b05_adopt_adopt tag found yet, will sleep 10 minutes and check again
No jdk8u402-b05_adopt_adopt tag found yet, will sleep 10 minutes and check again
No jdk8u402-b05_adopt_adopt tag found yet, will sleep 10 minutes and check again
No jdk8u402-b05_adopt_adopt tag found yet, will sleep 10 minutes and check again
```
This is caused by an _adopt tag being at the top of https://github.com/adoptium/jdk8u/tags (at this moment jdk8u402-b05-dryrun-ga_adopt is at the top). 
Can be fixed by either checking if _adopt is already in the retrieved tag, or by having a fixed order of what appears in https://github.com/adoptium/jdk8u/tags

**Comment by smlambert** [comment]
Update status template to remove 32bit platforms for jdk21 https://github.com/adoptium/temurin/pull/18

**Comment by smlambert** [comment]
TRSS seems to have slowed or stalled receiving and reporting test results, not sure why, whether its the Jenkins server at capacity when queried, or something on the TRSS server.  Needs investigation.

**Comment by jerboaa** [comment]
The release publish job seems to take the release name as input. Accidents can happen if the release name doesn't match the common pattern. E.g. `JDK-11.0.22+7` vs `jdk-11.0.22+7` (upper vs. lower case). Consider adding `.toLowerCase()` on the input string. Further refinements would be to configure the name ahead of time and make it a drop down or something.

**Comment by smlambert** [comment]
Tests running on aarch64 Linux nodes are painfully slow and hitting 10hr time limit, so aborting and need relaunching https://github.com/adoptium/aqa-tests/issues/4983#issuecomment-1896286171 (not seen during dry run)

**Comment by smlambert** [comment]
4 jdk21 windows testcases can not pass on ci.adoptium.net Jenkins machines, but can on temurin-compliance Jenkins machine (https://github.com/adoptium/aqa-tests/issues/4983#issuecomment-1896504690)

**Comment by sxa** [comment]
Release check script appears to have a bug, but I was superficially unable to repliate this on my local machine.
https://github.com/adoptium/github-release-scripts/issues/145
```
AIX on ppc64: Not published:
../sbin/releaseCheck.sh: 62: [: x64: unexpected operator
../sbin/releaseCheck.sh: 62: [: aarch64: unexpected operator
Windows on x64: OK!
```

**Comment by jerboaa** [comment]
> Release check script appears to have a bug, but I was superficially unable to repliate this on my local machine. [adoptium/github-release-scripts#145](https://github.com/adoptium/github-release-scripts/issues/145)
> 
> ```
> AIX on ppc64: Not published:
> ../sbin/releaseCheck.sh: 62: [: x64: unexpected operator
> ../sbin/releaseCheck.sh: 62: [: aarch64: unexpected operator
> Windows on x64: OK!
> ```

Same as https://github.com/adoptium/temurin/issues/13#issuecomment-1900826057 ?

**Comment by smlambert** [comment]
https://ci.adoptium.net/job/openjdk_build_docker_multiarch/ running on test-sxa-armv7l-ubuntu2004-odroid-2 and making it unavailable, which is the only online machine arm_linux machine where certain openjdk tests are known to pass (the other static docker nodes are not configured to allow for a green run of sanity.openjdk and extended.openjdk test targets).

**Comment by smlambert** [comment]
release tool: jdk8 x32 windows, I missed the .msi files in this [job](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8072/)

When I went to correct the mistake by uploading the 2 missing msi files in this [job](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8073/console) (and others varyiing the regex), hit this error:
```
+ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 bash ./sbin/Release.sh
Processing archive file: OpenJDK8U-jdk_x86-32_windows_hotspot_8u402b06.msi
sed: can't read OpenJDK8U-jdk_x86-32_windows_hotspot_8u402b06.msi.sha256.txt: No such file or directory
Build step 'Execute shell' marked build as failure
```
Also noting that the verifying Checks when uploading are helpful (indicated 21/23 files were uploaded), but would also be helpful to see this in a Dry run, as it would then help avert more problems.

Will be good to move to our more user-friendly wrapper job (that is now ready to deploy) practicing using it before next release period.

**Comment by sxa** [comment]
https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8089/ was published with a name missing the `jdk-` prefix, but the releaseCheck.sh didn't show it as everything abnormal - it seems to have found the right release - perhaps because it was a substring of the 'real' value - something to look at it in the releaseCheck.sh script as a potential buglet.

**Comment by smlambert** [comment]
https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8104/console reports an error when publishing jdk11 release notes

release script verification appears to run a check against Mac aarch64 during this run
```
MacOS on aarch64: INCOMPLETE: 62/31 (Expect jre, jdk, pkg-jre, pkg-jdk, testimage (Not JDK8), debugimage, static-libs (Not JD8) in base, json, sha256, sig)
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.22_7-metadata.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.22_7.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.22_7.json.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7.1/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-debugimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.pkg.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jdk_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.pkg.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-jre_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.22_7-metadata.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.22_7.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-sbom_aarch64_mac_hotspot_11.0.22_7.json.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-static-libs_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.json
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sha256.txt
https://github.com/adoptium/temurin11-binaries/releases/download/jdk-11.0.22%2B7/OpenJDK11U-testimage_aarch64_mac_hotspot_11.0.22_7.tar.gz.sig
Source images: Not complete:
```

Not seen when publishing release notes for JDK8, JDK17 and JDK21

**Comment by sophia-guo** [comment]
https://github.com/adoptium/temurin/issues/13#issuecomment-1908829962

aarch64_mac release [jdk-11.0.22+7.1](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.22%2B7.1) and jdk-11[jdk-11.0.22+7](https://github.com/adoptium/temurin11-binaries/releases/tag/jdk-11.0.22%2B7).

Uploading OpenJDK11U-jdk-release-notes_11.0.22_7.json is using tag jdk-11.0.22+7,  and releaseCheck.sh is checking doubled aarch64_mac files. If it's uploading release notes only might just skip check process.

**Comment by sxa** [comment]
@smlambert @sophia-guo My gut feel from the output is that this is likely another symptom of [my comment above](https://github.com/adoptium/temurin/issues/13#issuecomment-1908505870) where it's finding artefacts that are in a tag which is superset of others - in this case I would guess that it's picking up and counting all artefacts in releases that are in jdk-11.0.22+7.1 as well as jdk-11.0.22+7 so finding twice as many.

e.g. in my comment a parameter to the check script of `20.0.2+13` counted artifacts in `jdk-20.0.2+13` and I think in your example `jdk-11.0.22+7` is probably additionally counting things in `jdk-11.0.22+7.1` (Both have mac/aarch64 artifacts in them so it finds twice as many as expected so declares an error condition)

> If it's uploading release notes only might just skip check process.

I think it would be better to add the release notes into the check in the same way as we do for the source archive (Noting also that Shelley's log above shows `Source images: Not complete:` which we should probably fix)

**Comment by sophia-guo** [comment]
Night tests are disabled during releases. However if Pr in ci-jenkins-pipeline is merged during the releases the tests will be re-enabled again as jobs are regenerated.

**Comment by smlambert** [comment]
Shelley action: Go through Post-release actions from AQAvit triage issues and create issues for them

**Comment by adamfarley** [comment]
**Retrospective actions summary**

Adam:
- https://github.com/adoptium/temurin/issues/13#issuecomment-1890962636
  - Backport needed? Raise issue.
- https://github.com/adoptium/temurin/issues/13#issuecomment-1908505870
  - Raise issue
- https://github.com/adoptium/temurin/issues/13#issuecomment-1914789028
  - Raise issue
- Update relevant comment to reflect the raising of: https://github.com/adoptium/installer/issues/811 

Shelley: Go through Post-release actions from AQAvit triage issues and create issues for them

**Comment by smlambert** [comment]
Suggest that the banner gets taken down when the blog post is published, since that is an appropriate time to mark the end of the release.  (noting our banner is still up, and we are completed the main aspects of the release at this time).
