### ISSUE TITLE
Checklist for Temurin Release March 2024

### ISSUE THREAD

**Issue by steelhead31** [adoptium/temurin#32]
**NOTE: Items marked `jdkxx` and `TEMPLATE_UPDATEME` should be replaced while deploying this issue template. It is recommended to delete this line once you've done so :-)**

This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.

The target release date is: 19th March 2024

The release champion for this release is: Scott Fryer

Planned absences during the release cycle:

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

### Two Weeks Prior To Release

- [X] **Release Champion named** whose responsibility is to ensure every item in this checklist gets completed
- [X] **Release Checklist Created**  Create this issue to track the release and the preparation tasks.
- [X] **Identify Expected Release Versions** - Find out the version numbers from [here](https://www.java.com/releases/) - JDK22.0.0

- [x] **Notify release branching of build repositories** : [Slack message, branching build repositories](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#branching-message-for-build-related-repositories)
- [x] **Create build repositories release Branches** : [Create build repository release branches](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#create-release-branch-on-below-repositories)

- [x] **Identify the aqa branch name for the upcoming release** - aqa-tests branch name is [v1.0.1-release](https://github.com/adoptium/aqa-tests/tree/v1.0.1-release)

Ensure ALL nodes online prior to running these following TC steps:
 - [x] TC: Run the DeleteJCKMultiNode process cleaning job on all ci.role.test nodes, to remove any now redundent jck-versions, to ensure healthy state, verify all nodes successful: https://ci.eclipse.org/temurin-compliance/job/DeleteJCKMultiNode
 - [x] TC: Run the ProcessCheckMultiNode process cleaning job on all ci.role.test nodes, to ensure healthy state, verify all nodes successful: https://ci.eclipse.org/temurin-compliance/job/ProcessCheckMultiNode/build?delay=0sec

**ALL OK - Except jck-skytap-aix72-ppc64-3 which is clean, but had issues with git, issue logged with EF Infra
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4419 NOW RESOLVED**

 - [x] TC: Run the Setup_JCK_Run_Multinode job with CLEAN_DIR=true (to purge any old release contents/results) on all ci.role.test nodes, this will extract the jck_run folder with all the temurin.jtx exclude files, verify all nodes successful : https://ci.eclipse.org/temurin-compliance/job/Setup_JCK_Run_Multinode/build?delay=0sec

 - [x] **Check the nagios server to ensure there are no critical infrastructure issues**
	 Log in to the public [nagios](https://nagios.adoptopenjdk.net/nagios/) server, and check the Problems / Services page. If you do not have access, please request it via an issue in the infrastructure repository. If there are any issues, then please log an issue in the infrastructure repository.
 - [x] **Regenerate The Release Build Pipeline Jobs In Jenkins**
 - https://ci.adoptium.net/job/build-scripts/job/utils/job/release-pipeline-generator/56/

 - [x] **Prepare & Perform Dry Run Of Build & Tests** : [Dry-run](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#auto-way---before-release-week-dry-run-release-test) 
https://ci.adoptium.net/job/build-scripts/job/release-openjdk22-pipeline/4/ 

 - [x] **Triage dry-run TCK job results**
 - [x] **Restore aqa-tests release branch testenv.properties JDK_BRANCH values to the "-ga" tag after dry-run has completed**
 - [x] ~~**Perform TCK Auto-manuals on x64Linux for each dry-run version**~~

### One Week Prior To Release
- [x] **Final Code Freeze Warning** post a message to the build & release slack channels : [Slack message](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#code-freeze-message)

After 1 day, then :-

- [x] **Declare code freeze** to ensure stability of build systems and infrastructure during release process : #build and #release slack message: "Code Freeze is now being enabled"

- [x] **Enable code freeze bot** : [Enabling code freeze](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#enable-code-freeze-on--main-branches-of-below-repositories)

- [x] **Prepare For Release**
  - [x] Ensure that there is an [aqa-tests branch](https://github.com/adoptium/aqa-tests/branches) that matches the name of the [latest aqa-tests release version](https://github.com/adoptium/aqa-tests/releases/latest).  This checklist item is a wordier dup of 'Identify the aqa branch name' step above  [v1.0.1-release](https://github.com/adoptium/aqa-tests/tree/v1.0.1-release)
  - [x] Update [releaseVersions](https://github.com/adoptium/ci-jenkins-pipelines/blob/187d92c3030354557b2fc105cbff3e5ec631674c/pipelines/build/regeneration/release_pipeline_generator.groovy#L10C35-L10C35) with release versions.
  - [x] Update [releasePlan.cfg](https://github.com/adoptium/mirror-scripts/blob/master/releasePlan.cfg) with expected tags, for more detail see [here](https://github.com/zdtsw/mirror-scripts/tree/issue/3167#skara-repos-and-processes).
  - [x] Generate release pipeline jobs with [release-pipeline-generator](https://ci.adoptopenjdk.net/job/build-scripts/job/utils/job/release-pipeline-generator).
    - DO NOT use default job parameter values. aqaReference should be the [latest aqa-tests release version](https://github.com/adoptium/aqa-tests/releases/latest).

**Wait For All Of The Above To Complete Successfully Before Proceeding!**

- [x] Log a helpdesk ticket with EF , to get all test materials updated
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4437
- [x] TC: Run the ProcessCheckMultiNode process cleaning job on all ci.role.test nodes, to ensure healthy state, verify all nodes successful: https://ci.eclipse.org/temurin-compliance/job/ProcessCheckMultiNode/build?delay=0sec
- [x] TC: Run the Setup_JCK_Run_Multinode job with CLEAN_DIR=true (to purge any old release contents/results) on all ci.role.test nodes, this will extract the jck_run folder with all the temurin.jtx exclude files, verify all nodes successful : https://ci.eclipse.org/temurin-compliance/job/Setup_JCK_Run_Multinode/build?delay=0sec
- [x] Check the nagios server to ensure there are no critical infrastructure issues
- [x] ~~**Trigger a trial release pipeline dry-run** to ensure less surprises on release day (typically against a milestone build), see here for [details](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#auto-way---before-release-week-auto-test)~~

- [x] ~~Confirm successful trial release pipelines and successful jck completion~~
- [x] ~~Calculate the "expected" openjdk build tags for the releases being published, and update all the JDKnn_BRANCH values in the testenv.properties file for the aqa-tests release branch, eg: https://github.com/adoptium/aqa-tests/blob/v0.9.6-release/testenv/testenv.properties~~ Should no longer be needed for main openjdk branches, still need to pay attention to arm32 JDK8 which does not follow predictable tagging.

-------

Release Week Checklist:

- [x]   -- Check All Nodes Online https://ci.eclipse.org/temurin-compliance/label/ci.role.test/
[- [X] ](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4438)
- [x]  Run https://ci.eclipse.org/temurin-compliance/job/ProcessCheckMultiNode/ -- with defaults
- [x] Run Setup_JCK_Multinode with CLEAN_DIR=true for ( ci.role.test )
- [x] Disable Setup_JCK_Run_Multinode To Ensure Test Evidence Is Not Lost
- [x] As detailed earlier, again check the nagios server to ensure there are no critical infrastructure issues
- [x] Create the Github Issues for tracking progress against each Java version in the adoptium/temurin repo
- [x] Create the Github issues for the Adoptium public retro & TC retro in the adoptium/temurin repo
- [x] Update the links on the slack channel for the release status and retrospective issues.

#### Release Day Onwards

- [x] **Check Tags have been released upstream** - Look for mailing list announcements and `-ga` tags in version control.
- [x] ~~Check the published GA tags are the "expected" tags entered in the aqa-tests release branch testenv.properties. If they are not then update.~~ No longer needed and a dup of step above 'Calculate the "expected" openjdk build tags', Will only need to update arm32 JDK8, as the branch it lives in does not follow same tagging rules as others.
- [x] **Check Tags have been Mirrored** [Mirrors](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/).
- [x] **Check "auto-trigger" pipelines or Launch build pipelines** for each version being released. Verify if the release pipline "auto-triggered", if not (maybe expected tag was wrong), then manually launch [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk8 pipeline(s):
    - **primary jdk8 pipeline:**
      - rerun(s):
    - **secondary jdk8 pipeline:**
      - reruns(s):
  - jdk11 pipeline(s):
    - **primary jdk11 pipeline:**
      - rerun(s):
    - **secondary jdk11 pipeline:**
      - rerun(s):
  - jdkxx pipeline(s):
    - **primary jdkxx pipeline:**
      - rerun(s):
    - **secondary jdkxx pipeline:**
      - rerun(s):
- [x] ~~**Check Upstream Tags, Mirror Tags & Trigger Builds For JDK8 AARCH32** This specific version is built from a separate mirror repository and has a separate build process, this is CURRENTLY not part of the automation which is handled for the other platforms and version. Also note that there is a separate properties file (testenv_arm32.properties) in the aqa-tests release branch that needs to be updated.~~ Not required for this release
- [x] **Add links to the [status doc](https://github.com/adoptium/temurin/issues/TEMPLATE_UPDATEME)** to indicate per-platform builds ready
- [x] **Add website banner**
  - [x] Make a PR. [Link](https://github.com/adoptium/adoptium.net/pull/2726)
  - [x] Check it was automatically published to the website.
  - [x] Announce that we target releases to be available within 48-72 hours of the GA tags being available.
- [x] **Remind** TCK testers (via Slack comment) to update a TCK triage issue with ownership and machine IP **before** running any interactive/automanual tests.
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment.
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdk22 triage summary: https://github.com/adoptium/aqa-tests/issues/5156
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [x] **Generate The Release Notes Per JDK Version **, ( Use https://ci.adoptium.net/job/build-scripts/job/release/job/create_release_notes/ ) https://ci.adoptium.net/job/build-scripts/job/release/job/create_release_notes/72/
- [x] **Publish the release** (Find the quick links at the bottom of the Jenkins release pipeline job and run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins) ( also publish release notes - Done: https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/OpenJDK22U-jdk-release-notes_22_36.json)
- [x] **Consider updating the API** as required via the relevant parts of [the Adoptium API model constants](https://github.com/adoptium/api.adoptium.net/blob/main/adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Versions.kt).
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)

- [x] **Publish updates to the containers to dockerhub**
- [x] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb)** and replace the version and sha256 as appropriate.  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish.
- [x] **Update support page** (_automate_* github workflow to create a PR to update [support webpage](https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/supported-platforms/index.adoc)) https://github.com/adoptium/adoptium.net/pull/2760
- [x] **Update release notes** (_automate_* - github workflow to create update for release notes pages - [example](https://adoptium.net/temurin/release-notes/?version=jdk8u382-b05))
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
- [x] **Publicize the release** via Slack #release channel and Twitter (can be partially automated)
- [x] **Declare code freeze end** opening up the code for further development
- [x] **Disable code freeze bot** In order to enable the code freeze GitHub you need to change the line `if: github.repository_owner == 'adoptium' && true` to be `if: github.repository_owner == 'adoptium' && false` in the [code-freeze.yml](https://github.com/adoptium/.github/blob/main/.github/workflows/code-freeze.yml#L21) GitHub workflow. Please contact the PMC if you need help merging this change.
- [x] **Remove website banner** (_automate_* via github workflow in website repository)
- [x] **Check for presence of jdk8u aarch32 GA tag and mirror it** [Mercurial repo](https://hg.openjdk.java.net/aarch32-port/jdk8u) - [Mirror job](https://ci.adoptopenjdk.net/view/git-mirrors/job/git-mirrors/job/adoptium/job/git-hg-aarch32-jdk8u/)
- [x] **Do all of the above for the jdk8u/aarch32 build: Ensure to specify overridePublishName param**
- [x] **Archive/upload all TCK results** [ArchiveJCK_RunResults/31/](https://ci.eclipse.org/temurin-compliance/view/Grinder/job/ArchiveJCK_RunResults/31/) -> temurin-compliance-results/releases/tag/2024_March
- [x] **Publish AQAvit TAP files to the relevant releases repositories** - documentation forth-coming, combine the artifact from [TAP_verification/53](https://ci.adoptium.net/view/Test_grinder/job/TAP_verification/53/) with Grinder TAP files (19 gathered from triage activity at https://github.com/adoptium/aqa-tests/issues/5156#issuecomment-2035183719) and upload via this run [refactor_openjdk_release_tool/8457](https://ci.adoptium.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/8457/) to push to binaries repo ([here](https://github.com/adoptium/temurin22-binaries/releases/download/jdk-22%2B36/AQAvitTapFiles.tar.gz))
- [x] **Use EclipseMirror job in the Temurin Compliance jenkins to store a backup** of the release artifacts ([EclipseMirror/78](https://ci.eclipse.org/temurin-compliance/job/EclipseMirror/78/))
- [x] **Declare the release complete** and close this issue
- [x] **Create an issue for a release blog post for next release** in the [adoptium.net](https://github.com/adoptium/adoptium.net/pulls) repository and ensure to delegate the task of finalizing and publishing the existing draft PR for this release's blog post.  see https://github.com/adoptium/adoptium.net/issues/2756

**Comment by steelhead31** [comment]
Add new sections related to adding a new version to this checklist...   
  
1) Branch helper repo  
2) Add TCK new version  
3) Add ci-jenkins-pipeline release.groovy

**Comment by smlambert** [comment]
Think the only thing that remains is the update to the support page, fyi @sxa you can close this checklist issue after you are done with it

> Update support page (automate* github workflow to create a PR to update [support webpage](https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/supported-platforms/index.adoc)) @sxa volunteered to do so, as he was also going to update to include RISC-V

**Comment by steelhead31** [comment]
Release has been completed, so closing.
