### ISSUE TITLE
Checklist for Temurin Release 21.0.2+13 on linux-riscv64

### ISSUE THREAD

**Issue by sxa** [adoptium/temurin#33]
**NOTE: Items marked `jdkxx` and `TEMPLATE_UPDATEME` should be replaced while deploying this issue template. It is recommended to delete this line once you've done so :-)**

This Temurin release checklist based on the [release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md) captures what activities must happen during a release.

The target release date is: 13 March 2025

The release champion for this release is: @sxa

Planned absences during the release cycle:

The role of the release champion is to ensure that all release activities listed in this checklist get completed (by delegation to the broader team or by the release champion themselves).  The final task of the release champion during a release is to confirm that all items in the checklist were completed satisfactorily and the release can be declared complete.

Everyone participating in a release, including the release champion are requested to provide feedback into the release retrospective so that the release process can be continuously improved (through simplification and/or automation).

-------

- [ ] **Check "auto-trigger" pipelines or Launch build pipelines** for each version being released. Verify if the release pipline "auto-triggered", if not (maybe expected tag was wrong), then manually launch [(as per release doc](https://github.com/adoptium/temurin-build/blob/master/RELEASING.md#steps-for-every-version)) once release tags are available via [launch page](https://ci.adoptopenjdk.net/job/build-scripts/job/openjdk8-pipeline/build) in Jenkins.  Provide links in this issue to each version's pipeline build(s). There may be multiple pipelines per version if primary and secondary platforms are separated to expedite the release.  In some cases,  where there are unforeseen configuration or infrastructure issues, reruns may be needed.
  - jdk21 pipeline(s):
    - **primary jdkxx pipeline:** **https://ci.adoptium.net/job/build-scripts/job/release-openjdk21-pipeline/25/**
- [ ] **Add links to the [status doc](https://github.com/adoptium/temurin/issues/TEMPLATE_UPDATEME)** to indicate per-platform builds ready
- [ ] **Add website banner** n/a since this is an additional release and not time critical
  - [ ] Make a PR.
  - [ ] Check it was automatically published to the website.
  - [ ] Announce that we target releases to be available within 48-72 hours of the GA tags being available.
- [ ] **Remind** TCK testers (via Slack comment) to update a TCK triage issue with ownership and machine IP **before** running any interactive/automanual tests.
- [x] **Summarize test results**.  Find each launched build pipeline in [TRSS](https://trss.adoptium.net/) to view a summary of test results.  Can use the Release Summary Report feature in TRSS to generate a summary of failures, history and possible issues in markup format to be added to this issue as a comment. See link in next bullet point
- [x] **Triage** each build and test failure in the release summary report (following the [Triage guidelines](https://github.com/adoptium/aqa-tests/blob/master/doc/Triage.md)) and determine blocking or non-blocking.  Supply links to triage issues or docs for each version here.
  - jdkXX triage summary: **https://github.com/adoptium/aqa-tests/issues/4976#issuecomment-1985959009**
- [x] **Fix** blocking failures if they exist and confirm others are non-blocking.
- [x] **Confirm Temurin-compliance items completed**, per platform/version/binaryType
- [x] **Get PMC 'ready to publish' approval**, once no blocking failures exist.
- [ ] **Generate The Release Notes Per JDK Version **, ( Use https://ci.adoptium.net/job/build-scripts/job/release/job/create_release_notes/ ) **n/a as this is not a new release**
- [x] **Publish the release** (run the restricted access [release tool job](https://ci.adoptopenjdk.net/job/build-scripts/job/release/job/refactor_openjdk_release_tool/) on Jenkins) ( also publish release notes )
- [ ] **Consider updating the API** as required via the relevant parts of [the Adoptium API model constants](https://github.com/adoptium/api.adoptium.net/blob/main/adoptium-models-parent/adoptium-api-v3-models/src/main/kotlin/net/adoptium/api/v3/models/Versions.kt).
- [x] **Verify binaries published successfully** to github releases repo and website (_automate_*, this could also be an automated test)

- [ ] **Publish updates to the containers to dockerhub** (May be blocked by the [lack of any official images to base on](https://github.com/docker-library/official-images/issues/16302) for this platform)
- [ ] **Edit the [Homebrew Temurin Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/temurin.rb)** and replace the version and sha256 as appropriate.  This means for Homebrew users that they install the latest by default and can use the `@` notation to install older versions if they wish. **n/a as this is not macos**
- [x] **Update support page** (_automate_* github workflow to create a PR to update [support webpage](https://github.com/adoptium/adoptium.net/blob/main/content/asciidoc-pages/supported-platforms/index.adoc)) https://github.com/adoptium/adoptium.net/pull/2760
- [ ] **Update release notes** (_automate_* - github workflow to create update for release notes pages - [example](https://adoptium.net/temurin/release-notes/?version=jdk8u382-b05)) [Separate release blog has been posted](https://adoptium.net/en-GB/blog/2024/04/eclipse-temurin-21-and-22-available-on-riscv/) and since this is not a new code version a release notes update is not required
- [x] **Trigger linux installers pipeline** currently it is part of the build pipelines (will eventually be updated to run independently)
- [x] **Publicize the release** via Slack #release channel and Twitter (can be partially automated) Done via blog post
- [ ] **Declare code freeze end** opening up the code for further development **n/a as this was not enabled for this new platform**
- [ ] **Disable code freeze bot** In order to enable the code freeze GitHub you need to change the line `if: github.repository_owner == 'adoptium' && true` to be `if: github.repository_owner == 'adoptium' && false` in the [code-freeze.yml](https://github.com/adoptium/.github/blob/main/.github/workflows/code-freeze.yml#L21) GitHub workflow. Please contact the PMC if you need help merging this change. **n/a as this was not enabled for this new platform**
- [ ] **Remove website banner** (_automate_* via github workflow in website repository) **n/a as this was not enabled for this new platform**
- [ ] **Archive/upload all TCK results**
- [x] **Use EclipseMirror job in the Temurin Compliance jenkins to store a backup** of the release artifacts
- [x] **Declare the release complete** and close this issue
- [ ] **Create a draft PR for a release blog post for next release** in the [adoptium.net](https://github.com/adoptium/adoptium.net/pulls) repository and ensure to delegate the task of finalizing and publishing the existing draft PR for this release's blog post. **n/a as it will be covered by the general one for the next version**

**Comment by sxa** [comment]
Closing this as the remaining issue was related to docker images and that does not yet have a resolution due to the equivalent base images not being available to us. The new release in April has also gone through without any additional issues including RISC-V for jdk21 and 22.
