### ISSUE TITLE
EPIC: Add more release metrics for Eclipse Temurin

### ISSUE THREAD

**Issue by jiekang** [adoptium/temurin#58]
We should continue to add relevant metrics around Eclipse Temurin to understand how our work is progressing, and how our work is being used.

This epic tracks related work on this topic:

- [ ] Time taken to publish installers
- [ ] Time taken to publish container images
- [ ] Number of downloads for installers
